# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory to /app
WORKDIR /app

# Copy entire repository to container
COPY . .

# Upgrade pip and install the package in editable mode using pyproject.toml configuration
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -e .

# Change working directory to the python module directory, as the MCP server expects to run from here
WORKDIR /app/src/python

# Expose port 8000 if needed (adjust if the server uses a different port)
EXPOSE 8000

# Default command to run the MCP server
CMD [ "python", "-m", "azure_agent_mcp_server" ]
